---
- name: install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
    cache_valid_time: 86400
  with_items: redmine_apache_subversion_packages
  notify: restart

- name: apache modules
  apache2_module:
    name: '{{ item }}'
  with_flattened:
  - redmine_apache_subversion_modules
  - '{{ redmine_apache_subversion_https_fix_modules if redmine_apache_subversion_https_fix else [] }}'
  notify: restart

- name: folder
  file:
    dest: '{{ redmine_apache_subversion_folder }}'
    state: directory
    owner: '{{ redmine_apache_subversion_folder_user }}'
    group: '{{ redmine_apache_subversion_folder_group }}'
    mode: '2775' # include the change group bit

- name: create script
  copy:
    src: 'svn_createrep.sh'
    dest: '{{ redmine_apache_subversion_folder }}/{{ redmine_apache_subversion_create_script_name }}'
    mode: '700'
  when: redmine_apache_subversion_create_script_name != ''

- name: fix permission script
  copy:
    src: 'svn_fixpermissions.sh'
    dest: '{{ redmine_apache_subversion_folder }}/{{ redmine_apache_subversion_fix_script_name }}'
    mode: '700'
  when: redmine_apache_subversion_fix_script_name != ''

- name: apache conf
  template:
    dest: "{{ redmine_apache_server_sites_include_folder }}/{{ redmine_apache_subversion_vhost }}/{{ redmine_apache_subversion_config_name }}.conf"
    src: 'redmine_subversion.conf.j2'
  notify: restart
