---
- name: echo DATABASE_URL
  shell: "{{ profile }}'echo $DATABASE_URL'"
  changed_when: no
  register: redmine_database_url_result
  tags: [always]

- name: fact DATABASE_URL
  set_fact:
    DATABASE_URL: "{{ redmine_database_url_result.stdout }}"
  tags: [always]

- name: database.yml
  template:
    dest: "{{ redmine_release_path }}/config/database.yml"
    src: "database.yml.j2"

- name: secret_token.rb
  template:
    dest: "{{ redmine_release_path }}/config/initializers/secret_token.rb"
    src: "secret_token.rb.j2"
    mode: "600"

- name: secrets.yml
  template:
    dest: "{{ redmine_release_path }}/config/secrets.yml"
    src: "secrets.yml.j2"
    mode: "600"

- name: redmine config
  template:
    dest: "{{ redmine_release_path }}/config/configuration.yml"
    src: configuration.yml.j2

- name: no additional_environment.rb
  file:
    dest: "{{ redmine_release_path }}/config/additional_environment.rb"
    state: absent
  when: not ((redmine_additional_env is sequence) and (redmine_additional_env is not string) and (redmine_additional_env | length > 0))

- name: additional_environment.rb
  template:
    dest: "{{ redmine_release_path }}/config/additional_environment.rb"
    src: "additional_environment.rb.j2"
  when: (redmine_additional_env is sequence) and (redmine_additional_env is not string) and (redmine_additional_env | length > 0)
