---
- name: echo DATABASE_URL
  shell: "{{ profile }}'echo $DATABASE_URL'"
  changed_when: no
  register: redmine_database_url_result
  tags:
  - facts

- name: fact DATABASE_URL
  set_fact:
    DATABASE_URL: "{{ redmine_database_url_result.stdout }}"
  tags:
  - facts

- name: database.yml
  template:
    dest: "{{ redmine_release_path }}/config/database.yml"
    src: "database.yml.j2"

- name: secret_token.rb
  copy:
    dest: "{{ redmine_release_path }}/config/initializers/secret_token.rb"
    content: "RedmineApp::Application.config.secret_token = ENV['SECRET_KEY_BASE']"
    mode: "600"
