---
- name: echo DATABASE_URL
  shell: "{{ profile }}'echo $DATABASE_URL'"
  changed_when: no
  register: redmine_database_url_result
  tags: [always]

- name: fact DATABASE_URL
  set_fact:
    DATABASE_URL: "{{ redmine_database_url_result.stdout }}"
  tags: [always]

- name: database.yml
  template:
    dest: "{{ redmine_release_path }}/config/database.yml"
    src: "database.yml.j2"

- name: secret_token.rb
  template:
    dest: "{{ redmine_release_path }}/config/initializers/secret_token.rb"
    src: "secret_token.rb.j2"
    mode: "600"

- name: secrets.yml
  template:
    dest: "{{ redmine_release_path }}/config/secrets.yml"
    src: "secrets.yml.j2"
    mode: "600"

- name: redmine config
  template:
    dest: "{{ redmine_release_path }}/config/configuration.yml"
    src: configuration.yml.j2
